TOPMODEL_params: &TOPMODEL_params
  -
      name: t0
      min: -8
      max: 8
      init: 5
  -
      name: szm
      min: 0.001
      max: 1.0
      init: 0.032

  -
      name: srmax
      min: 0.001
      max: 1
      init: 0.355

  -
      name: xk0
      min: 0.0
      max: 0.01
      init: 0.001

  -
      name: chv
      min: 10
      max: 25000
      init: 3600

  -
      name: rv
      min: 1
      max: 5000
      init: 1000

general:
  iterations: 3
    # log_file: test_log
  # log refers to general log, not objective log
  log: True 
  start_iteration: 0
  strategy:
    algorithm: dds
    type: estimation
  workdir: /home/west/Projects/CAMELS/CAMELS_Files_Ngen/camels_10259000_22592131/
model:
  binary: ./ngen/cmake_build/ngen
  catchments: ./spatial/catchment_data.geojson
  crosswalk: ./parameters/cross-walk.json
  nexus: ./spatial/nexus_data.geojson
  partitions: partition_config.json
  parallel: 1
  params:
    TOPMODEL: *TOPMODEL_params
      # realization: Realization_noahowp_Topmodel_calibNC.json
      # realization: Realization_pet_Topmodel_calibNC.json
  realization: Realization_noahowp_pet_Topmodel_calibNC.json
  strategy: uniform
  type: ngen
  eval_params:
    evaluation_start: '2007-01-02 00:00:00'
    evaluation_stop: '2007-09-01 00:00:00'
    # objective: nnse
    objective: kling_gupta
    target: 'max'

